<a href="https://colab.research.google.com/github/sukhadak11/Machine_Learing/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

advantages of Numpy arrays:

 1.Allows several mathematical operations
 2. faster operations


In [ ]:
 import numpy as np

List vs Numpy - time taken


In [ ]:
from time import process_time

time taken by a list


In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001017183000000088


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 #np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)




0.0008414900000000003


Numpy arrays


In [ ]:
list1 = [1,2,3]
print(list1)
type(list1)

[1, 2, 3]


list

In [ ]:
np_array = np.array([1,2,3])
print(np_array)
type(np_array)

[1 2 3]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays

In [ ]:
# create a numpy arrya of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy arrya of zeros
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# arrya of a particular value
z=np.full((5,4),5) # full function for particular value
print(z)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.76060587 0.13681849 0.19708605 0.89019051]
 [0.13257033 0.60950516 0.63392629 0.10318107]
 [0.48357743 0.63405563 0.25272787 0.19995304]]


In [ ]:
# random integer values array within a sepcific range
c = np.random.randint(10,100,(3,5))
print(c)

[[50 61 94 85 76]
 [31 39 73 18 65]
 [70 24 19 27 24]]


In [ ]:
# array of evenly spaced values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[29 78 20 45 21]
 [61 17 56 12 34]
 [22 45 22 81 17]
 [85 75 12 38 80]
 [54 75 27 87 21]]


In [ ]:
# array dimension
print (c.shape)

(5, 5)


In [ ]:
# number of dim
print(c.ndim)

2


In [ ]:
# no. of aeeay
print(c.size)

25


Mathematical opweation

In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,20,(3,3))

In [ ]:
print(a)
print(b)

[[2 9 7]
 [8 9 4]
 [1 6 5]]
[[15 17 11]
 [19 18  7]
 [16 15  5]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 26 18]
 [27 27 11]
 [17 21 10]]
[[-13  -8  -4]
 [-11  -9  -3]
 [-15  -9   0]]
[[ 30 153  77]
 [152 162  28]
 [ 16  90  25]]
[[0.13333333 0.52941176 0.63636364]
 [0.42105263 0.5        0.57142857]
 [0.0625     0.4        1.        ]]


In [ ]:
array  = np.random.randint(0,10,(2,3))
print(array)
print(array. shape)


[[0 5 1]
 [2 0 7]]
(2, 3)


In [ ]:
np.transpose

In [ ]:
trans = np.transpose(array) #tranpo
print(trans)
print(trans.shape)

[[0 2]
 [5 0]
 [1 7]]
(3, 2)
